/* eslint-disable @typescript-eslint/no-non-null-asserted-optional-chain */
import Link from "next/link";
import Image from "next/image";

import { Button } from "@/components/ui/button";
import InterviewCard from "@/components/InterviewCard";
import { dummyInterviews } from "@/constants";

import { getCurrentUser } from "@/lib/actions/auth.action";
import {
  getInterviewsByUserId,
  getLatestInterviews,
} from "@/lib/actions/general.action";
import { AudioLines } from "lucide-react";

async function Home() {
  const user = await getCurrentUser();

  const [userInterviews] = await Promise.all([
    getInterviewsByUserId(user?.id!),
    getLatestInterviews({ userId: user?.id! }),
  ]);

  const hasPastInterviews = userInterviews?.length! > 0;

  return (
    <>
      <section className="card-cta">
        <div className="flex flex-col gap-6 max-w-lg">
          <AudioLines size={34} />
          <h2>Unlock Your Interview Potential with AI-Driven Practice & Insights</h2>
          <p className="text-lg">
            Master real interview questions and receive instant, actionable feedback to boost your confidence and skills.
          </p>
          <Button asChild className="bg-white w-48">
            <Link href="dashboard/interview">Generate An Interview</Link>
          </Button>
        </div>

        <Image
          src="/asset.png"
          alt="crystal"
          width={175}
          height={175}
          className="max-sm:hidden"
        />
      </section>

      <section className="flex flex-col gap-6 mt-8">

        <div>
          <h2>Your Interviews</h2>
          <p>Interviews generated by AI based on your criteria</p>
        </div>

        <div className="interviews-section">
          {hasPastInterviews ? (
            userInterviews?.map((interview) => (
              <InterviewCard
                key={interview.id}
                userId={user?.id}
                interviewId={interview.id}
                role={interview.role}
                type={interview.type}
                techstack={interview.techstack}
                createdAt={interview.createdAt}
                level={interview.level}
                isTemplate={false}
              />
            ))
          ) : (
            <p>You haven&apos;t taken any interviews yet</p>
          )}
        </div>
      </section>

      <section className="flex flex-col gap-6 mt-8">
        <div>
          <h2>Templates</h2>
          <p>Get started with a pre-made template</p>
        </div>

        <div className="interviews-section">
          {dummyInterviews ? (
            dummyInterviews?.map((interview) => (
              <InterviewCard
                key={interview.id}
                userId={user?.id}
                interviewId={interview.id}
                role={interview.role}
                type={interview.type}
                level={interview.level}
                techstack={interview.techstack}
                createdAt={interview.createdAt}
                isTemplate={true}
              />
            ))
          ) : (
            <p>There are no interviews available</p>
          )}
        </div>
      </section>
    </>
  );
}

export default Home;
