/* eslint-disable @typescript-eslint/no-non-null-asserted-optional-chain */
import Link from "next/link";
import Image from "next/image";

import { Button } from "@/components/ui/button";
import InterviewCard from "@/components/InterviewCard";
import { dummyInterviews, PRICING_PLAN_NAMES } from "@/constants";

import { getCurrentUser } from "@/lib/actions/auth.action";
import {
  getInterviewsByUserId,
} from "@/lib/actions/general.action";
import { AudioLines, CreditCard } from "lucide-react";
import { convertFirebaseTimestampToJSDate, isTrialExpired } from "@/lib/utils";

async function Home() {
  const user = await getCurrentUser() as User;

  const [userInterviews, trialExpired, trialExpirationDate] = await Promise.all([
    getInterviewsByUserId(user?.id!),
    isTrialExpired(),
    convertFirebaseTimestampToJSDate(user?.subscription?.trialExpiration)
  ]);

  const hasPastInterviews = userInterviews?.length! > 0;

  return (
    <>
      <section className="card-cta">
        <div className="flex flex-col gap-4 max-w-lg">
          <AudioLines size={34} />
          <h2 className="text-xl md:text-2xl">Unlock Your Interview Potential with AI-Driven Practice & Insights</h2>
          <div>
            <div className="flex flex-col md:flex-row md:items-center py-4">
              <p>Currently on <span className="capitalize bg-gradient-to-r font-semibold from-purple-400 via-pink-500 to-red-500 bg-clip-text text-transparent">{user?.subscription.plan}</span> plan</p>
              <Button variant={"outline"} className="w-max py-4 md:ml-8 mt-2 md:mt-0">
                <CreditCard color="white" />
                <Link className="text-white" href="/billing">Manage Billing</Link>
              </Button>
            </div>
            {
              user?.subscription.plan !== PRICING_PLAN_NAMES.TRIAL &&
              <p className="text-sm md:text-md text-[#A2A2A2] mt-1">Let's ace that interview 💪🏻</p>
            }
          </div>

          {
            (user?.subscription.plan === PRICING_PLAN_NAMES.TRIAL && !trialExpired) ?
              <div>
                <p className="text-sm md:text-md text-[#A2A2A2]">Liking it so far? Upgrade to continue using Mockero after the trial expires.</p>
                <p className="text-sm md:text-md text-[#A2A2A2]">Your trial expires on {trialExpirationDate?.toLocaleDateString()}</p>
              </div>
              :
              <div>
                <p className="text-sm md:text-md text-amber-400">Your trial has expired. Choose a plan to continue using Mockero.</p>
              </div>
          }

          <div className="flex flex-col md:flex-row justify-center md:justify-start md:items-center  mt-4">
            <Button disabled={trialExpired} className="bg-white w-max">
              <Link href="dashboard/interview">Generate An Interview</Link>
            </Button>
          </div>
        </div>

        <Image
          src="/asset.png"
          alt="crystal"
          width={175}
          height={175}
          className="max-sm:hidden"
        />
      </section>

      <section className="flex flex-col gap-6 mt-8">

        <div>
          <h2>Your Interviews</h2>
          <p>Interviews generated by AI based on your criteria</p>
        </div>

        <div className="interviews-section">
          {hasPastInterviews ? (
            userInterviews?.map((interview) => (
              <InterviewCard
                key={interview.id}
                userId={user?.id}
                interviewId={interview.id}
                role={interview.role}
                type={interview.type}
                techstack={interview.techstack}
                createdAt={interview.createdAt}
                level={interview.level}
                isTemplate={false}
                isTrialExpired={trialExpired}
              />
            ))
          ) : (
            <p>You haven&apos;t taken any interviews yet</p>
          )}
        </div>
      </section>

      <section className="flex flex-col gap-6 mt-8">
        <div>
          <h2>Templates</h2>
          <p>Get started with a pre-made template</p>
        </div>

        <div className="interviews-section">
          {dummyInterviews ? (
            dummyInterviews?.map((interview) => (
              <InterviewCard
                key={interview.id}
                userId={user?.id}
                interviewId={interview.id}
                role={interview.role}
                type={interview.type}
                level={interview.level}
                techstack={interview.techstack}
                createdAt={interview.createdAt}
                isTemplate={true}
                isTrialExpired={trialExpired}
              />
            ))
          ) : (
            <p>There are no interviews available</p>
          )}
        </div>
      </section>
    </>
  );
}

export default Home;
